---
title: "Notebook"
format: html
editor: visual
---

```{r}
library(here)
# Ejecutar cada etapa en orden
source(here("TP2/scripts/scraping_oea.R"))
source(here("TP2/scripts/processing.R"))
source(here("TP2/scripts/metrics_figures.R"))
```

La figura de frecuencias ubicada en la carpeta output, presenta las palabras más frecuentes identificadas en los comunicados de prensa publicados por la Organización de los Estados Americanos (OEA) durante los primeros meses de 2026. A partir del procesamiento y limpieza de los textos, se construyó una matriz documento-término (DTM) que permitió contabilizar la frecuencia de aparición de las principales palabras utilizadas en los comunicados oficiales.

La figura muestra que las palabras con mayor presencia son “estado”, “misión”, “oea”, “proceso” y “organización”. Esto sugiere que la comunicación institucional de la OEA se encuentra fuertemente orientada hacia cuestiones vinculadas con la actividad estatal, los procesos políticos y las misiones internacionales desarrolladas por el organismo.

La elevada frecuencia de la palabra “misión” puede asociarse al rol de la OEA en tareas de observación electoral, cooperación internacional y seguimiento institucional en distintos países de la región. Por otro, la aparición de términos como “estado” y “proceso” hace foco en el funcionamiento institucional.

La presencia reiterada de la propia sigla “OEA” y de la palabra “organización” evidencia el carácter institucional y diplomático de los comunicados analizados, ya que gran parte de los textos se enfocan en describir acciones, reuniones y declaraciones oficiales del organismo.
