---
title: "texto"
format: html
editor: visual
---

Librerías

```{r}
library(tidyverse)
library(udpipe)
library(here)
library(tidytext)
library(tm)


```

Cargar datos

```{r}
datos_oea <- readRDS(here("TP2/data/datos_oea.rds"))
```

Limpieza del cuerpo

```{r}
datos_oea <- datos_oea %>%
  mutate(cuerpo_limpio = str_to_lower(cuerpo)) %>%
  mutate(cuerpo_limpio = str_replace_all(cuerpo_limpio, "[^a-záéíóúñ\\s]", ""))

modelo <- udpipe_download_model(language = "spanish")
modelo <- udpipe_load_model(modelo$file_model)

anotado <- udpipe_annotate(modelo, x = datos_oea$cuerpo_limpio)
anotado <- as.data.frame(anotado)

```

Filtrado

```{r}
texto_procesado <- anotado %>%
  filter(upos %in% c("NOUN", "VERB", "ADJ")) %>%
  mutate(lemma = tolower(lemma))
```

Matriz DTM

```{r}
tokens <- texto_procesado %>%
  select(doc_id, lemma)

dtm <- tokens %>%
  count(doc_id, lemma) %>%
  cast_dtm(
    document = doc_id,
    term = lemma,
    value = n
  )

print(dtm)
```

Guardar

```{r}
saveRDS(texto_procesado, here("TP2/output/texto_procesado.rds"))

```
