---
title: "tp"
format: html
editor: visual
---

Librerias

```{r}
library(rvest)
library(tidyverse)
library(here)
```

Estructura links + loops noticias

```{r}
meses <- 1:4

resultados <- list()
id <- 1

for (mes in meses) {
  
  message("Mes: ", mes)
  
  url <- paste0(
    "https://www.oas.org/es/centro_noticias/comunicados_prensa.asp?nMes=",
    mes,
    "&nAnio=2026"
  )
  
  pagina <- read_html(url)
  
  items <- pagina %>%
    html_elements(".itemmenulink")
  
  titulos <- items %>%
    html_text(trim = TRUE)
  
  links <- items %>%
    html_attr("href")
  
  # limpiar
  datos_mes <- tibble(
    titulo = titulos,
    link = links
  ) %>%
    filter(!is.na(link)) %>%
    filter(str_detect(link, "comunicado_prensa.asp"))
  
  # armar links completos
  datos_mes <- datos_mes %>%
    mutate(link = paste0(
      "https://www.oas.org/es/centro_noticias/",
      link
    ))
  
  for (i in 1:nrow(datos_mes)) {
    
    link <- datos_mes$link[i]
    titulo <- datos_mes$titulo[i]
    
    noticia <- tryCatch(
      read_html(link),
      error = function(e) return(NULL)
    )
    
    if (is.null(noticia)) next
    
    cuerpo <- noticia %>%
      html_elements("#rightmaincol p") %>%
      html_text(trim = TRUE)
    
    cuerpo <- cuerpo[cuerpo != ""]
    cuerpo <- paste(cuerpo, collapse = " ")
    
    resultados[[id]] <- tibble(
      id = id,
      titulo = titulo,
      cuerpo = cuerpo
    )
    
    id <- id + 1
    
    Sys.sleep(2)
  }
}

```

Tabla con datos + guardado

```{r}
datos_oea <- bind_rows(resultados)

saveRDS(datos_oea, here("TP2/data/datos_oea.rds"))
```
